# This playbook will help to find the available C drive space in Windows hosts
# Enter the host in inventory file
# Execute the script
---
- name: Checking the available C drive space on destination servers
  gather_facts: false
  ignore_errors: yes
  hosts: all
  tasks:
    - name: Getting C drive space
      win_shell: ([Math]::Round(((gwmi Win32_LogicalDisk -Filter "DeviceID='C:'").Freespace / 1GB), 2))
      register: cdrive

    - name: Setting facts
      set_fact:
        input: "{{ [inventory_hostname] }}; {{ cdrive.stdout_lines  }}"
        filename: output

    - name: Exporting outputs
      export_out:
        data: "{{ input }}"
        output_file: "{{ filename }}"
      delegate_to: localhost
