#User add with var file
#Using hashed password with the salt value of "mytestsalt"
---
- name: user vars_files to create multiple users
  hosts: all
  vars_files:
    - userlist.txt
  tasks:
    - name: create users using loop
      user:
        name: "{{ item.un }}"
        shell: "{{item.shell }}"
        comment: "{{ item.cmnt }}"
        password: "{{ item.pass | password_hash('sha512', 'mytestsalt') }}" #Password will be hashed with sha512 cert
      loop: "{{ userlist }}" 