# To check the status of the service in a windows servers
# Service name is necessory to list the status
# Host servers should be in a Windows-Inventory

- name: Check and start Windows Update service if stopped
  hosts: all
  gather_facts: no
  ignore_errors: yes
  vars_prompt:
    - name: service
      prompt: Enter the service name tocheck the status
      private: false
    - name: output
      prompt: Enter the file name to save the output
      private: false

  tasks:
    - name: Get Windows Update service status
      win_service:
        name: "{{ service }}"
      register: update_service

    - name: Save the status in a output file 
      lineinfile:
        line: "{{ inventory_hostname }} ; Service: {{ update_service.display_name }} ; Status: {{ update_service.status }}"
        path: "/tmp/output/{{ output }}"
        create: yes
      delegate_to: localhost

    # - name: Start service if not running
    #   win_service:
    #     name: "{{ service }}"            ###It can be started / stopped
    #     state: started
    #     start_mode: manual    ###It can be manual / automatic / disabled
    #   when: update_service.state != "running"